### ISSUE TITLE
Keep Alive is not treated according to MQTT standard

### ISSUE THREAD

**Issue by psavyhin** [FreeRTOS/coreMQTT#233]
It was found that coreMQTT application that intensively sends messages to a cloud can't pass Device Advisor "Keep Alive" test.
Details are described in an attached doc.
[RD-MQTTKeepAlivetestissue-211122-1343.pdf](https://github.com/FreeRTOS/coreMQTT/files/10059365/RD-MQTTKeepAlivetestissue-211122-1343.pdf)

**Comment by ademyankov** [comment]
@psavyhin I noticed some weird behavior too... I think the issue here is that the FreeRTOS repo uses very old coreMQTT version 1.1.0. When I used the latest coreMQTT v.2.1.1 I don't see any issues anymore.

FreeRTOS manifest needs to be updated for the newest version. There are some minor changes in the API so the examples will probably require change as well.

**Comment by AniruddhaKanhere** [comment]
@psavyhin, this issue was resolved in PR: https://github.com/FreeRTOS/coreMQTT/pull/235

@ademyankov the FreeRTOS manifest is already updated to be beyond v2.1.1 commit. https://github.com/FreeRTOS/FreeRTOS/blob/main/manifest.yml#L41-L46. Did I miss something?


I am closing this issue. Please feel free to re-open this issue or create a new one if you think that there has been a mistake on my part.

Thank you.
