### ISSUE TITLE
TransportInterface_t.writev is no longer optional and must be provided?

### ISSUE THREAD

**Issue by jondurrant** [FreeRTOS/coreMQTT#238]
Been trying to port my code to v2.1.1 and getting crashes. It looks like the cause is that TransportInterface_t.writev has to be provided to MQTT_init. This used to be optional on v1.2.0.  Documentation does not mention this as now mandatory.

**Comment by rawalexe** [comment]
I believe this is because our previous version didn't initialize the `TransportInterface_t` struct at declaration. There is a pull request open to fix it that can be found [here](https://github.com/aws/aws-iot-device-sdk-embedded-C/pull/1845).  Please let us know if your problem is not fixed after the request is merged.

**Comment by rawalexe** [comment]
The problem has been patched with the new [PR](https://github.com/aws/aws-iot-device-sdk-embedded-C/pull/1845). I'm closing the issue but if it persists please do reopen it.
